# Dependencies
markdown:         kramdown

# Setup
title:            Abhijith Ragav
image:            "abhijith.jpg"
tagline:          'Research Intern at Synergy Labs@Carnegie Mellon.'
description:      'Research Intern at Synergy Labs@Carnegie Mellon.'
url:              https://abhijithragav.com
# baseurl:          ""

author:
  name:           'Abhijith Ragav'
  url:            https://github.com/abhijithragav

include:
  - _pages
  
