# Dependencies
markdown:         kramdown

# Setup
title:            Abhijith Ragav
image:            "abhijith.jpg"
tagline:          'CS Grad Student, Georgia Tech'
description:      'CS Grad Student, Georgia Tech'
url:              https://abhijithragav.com
# baseurl:          ""

author:
  name:           'Abhijith Ragav'
  url:            https://github.com/abhijithragav

include:
  - _pages
  
